version: '3.1'

services:
  app:
    build: .
    ports:
      - "8080:5000"
    networks:
      - app_db
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_db

networks:
  app_db:
    driver: bridge

volumes:
  postgres_data:
